// Writes supabase/lab-schema.sql: every migration, in the order the live
// database received them, as one file to paste into the SQL editor of an
// EMPTY Supabase project (the lab). Run it again whenever a fresh lab database
// is needed; day to day, new migrations are applied to the lab one at a time.
//
//   node scripts/lab-schema.mjs
//
// The order matters. The studio's tables were built in their own folder
// (studio/supabase/migrations) between the main folder's 022 and 023, and
// main 023 onwards refers to them.
//
// Never paste the result into the live project: it is the whole history, and
// the live database already has it.
import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const MAIN = join(ROOT, 'supabase/migrations')
const STUDIO = join(ROOT, 'studio/supabase/migrations')
const STUDIO_AFTER = 22

const list = (dir) => readdirSync(dir).filter((f) => f.endsWith('.sql')).sort().map((f) => join(dir, f))
const number = (path) => Number(path.split('/').pop().slice(0, 3))

export const migrationOrder = () => [
  ...list(MAIN).filter((f) => number(f) <= STUDIO_AFTER),
  ...list(STUDIO),
  ...list(MAIN).filter((f) => number(f) > STUDIO_AFTER),
]

// The live project dates from when Supabase gave the API roles access to every
// new table by itself, and the migrations were written leaning on that. New
// projects no longer do it, so the same behaviour is switched on for the
// length of the replay…
const BEFORE = `
alter default privileges for role postgres in schema public
  grant select, insert, update, delete on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant usage, select on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant execute on functions to anon, authenticated, service_role;
`

// …and switched off again at the end, so the lab is as strict as the live
// project becomes on 30 October 2026: a later migration that creates a table
// without granting access to it fails here first, not in front of people.
const AFTER = `
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
`

const banner = (text) => `\n-- ${'─'.repeat(74)}\n-- ${text}\n-- ${'─'.repeat(74)}\n`

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const files = migrationOrder()
  const out = [
    '-- Companheiro lab database: the whole schema, for an EMPTY Supabase project.',
    '-- Generated by scripts/lab-schema.mjs — do not edit, and never run on the live project.',
    banner('Access for the API roles while the history replays'),
    BEFORE,
    ...files.map((f) => `${banner(f.replace(ROOT + '/', ''))}\n${readFileSync(f, 'utf8').trim()}\n`),
    banner('From here on, new tables need their own grants (as on live from 30 Oct 2026)'),
    AFTER,
  ].join('\n')
  const target = join(ROOT, 'supabase/lab-schema.sql')
  writeFileSync(target, out)
  console.log(`${files.length} migrations → supabase/lab-schema.sql (${out.split('\n').length} lines)`)
}
